language: java
jdk:
- oraclejdk7
- openjdk6
- openjdk7
- oraclejdk8
script: ant clean-build
after_success: "./deploy.sh"
env:
  global:
    secure: uXH05twyRorFCMk8PtTem5EGZrQ31MkVnkPHxZbdlXUl8fDUkMVD3yRB8+pmGw/tTkx6Bjo6Q3VsaIOAgP+mP5QVsOD2XvZ8Dk/LTl2N4FUpyfUjdCwJt/qXUcwIJdbzIED29g05pLPBS3HSeyTRNzSvC5Rajc0yDXfx6A3z6RA=
